name: Build

on:
  workflow_call:
    inputs:
      ruby_version:
        type: string
        required: true
      node_version:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: yarn
      - run: yarn install --production=false
