name: Build

on:
  workflow_call:
    secrets:
      ruby_version:
        type: string
        required: true
      node_version:
        type: string
        required: true
      bundle_github__com:
        required: false

env:
  BUNDLE_GITHUB__COM: ${{ secrets.bundle_github__com }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ secrets.ruby_version }}
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.node_version }}
          cache: yarn
      - run: yarn install --production=false
