name: Build

on:
  workflow_call:
    inputs:
      ruby_version:
        type: string
        required: true
      node_version:
        type: string
        required: true
      cmd:
        type: string
        required: true
      cache_key:
        type: string
        required: false
        default: yarn
    secrets:
      bundle_github__com:
        required: false
env:
  BUNDLE_GITHUB__COM: ${{ secrets.bundle_github__com }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build rails
        uses: ePages-de/action-build-rails@master
        with:
          node_version: ${{ inputs.node_version }}
          ruby_version: ${{ inputs.ruby_version }}
      - name: node_run
        uses: ePages-de/action-node-run@master
        with:
          node_version: ${{ inputs.node_version }}
          cmd: ${{ inputs.cmd }}
          cache_key: ${{ inputs.cache_key }}
      - name: bundle_run
        uses: ePages-de/action-bundle-run@master
        with:
          node_version: ${{ inputs.node_version }}
          ruby_version: ${{ inputs.ruby_version }}