name: Rspec

on:
  workflow_call:
    inputs:
      ruby_version:
        type: string
        required: true
      node_version:
        type: string
        required: true
    secrets:
      bundle_github__com:
        required: false
      dotenv_content:
        required: false

env:
  BUNDLE_GITHUB__COM: ${{ secrets.bundle_github__com }}

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      RAILS_ENV: test
      REDIS_URL: redis://localhost:6379/0
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby_version }}
          bundler-cache: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ inputs.node_version }}
          cache: yarn
      - run: yarn install --production=false
      - run: echo $DOTENV_CONTENT | base64 -d > .env
        env:
          DOTENV_CONTENT: ${{ secrets.dotenv_content }}
      - run: sudo apt-get -y install libpq-dev
      - run: bundle exec rails db:create db:schema:load --trace
      - run: bundle exec rspec
      - uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage
          path: coverage
